apiVersion: v1
kind: Pod
metadata:
  name: test-pod-01
  namespace: logging
spec:
  containers:
  - name: app
    image: httpd
    volumeMounts:
    - name: persistent-storage
      mountPath: /var/neeteshappscoop
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: azurefile-pvc-01
